name: pr
description: pull requestの詳細
title: "[PR]: "
body:
  - type: textarea
    id: description
    attributes:
      label: 作業内容
      description: このPRで行う変更内容を記載してください。
      placeholder: |
        ログイン機能を追加する
        1. 入力フォームの実装
        2. バリデーション機能の調査
        3. バリデーション機能の実装
        4. DBのスキーマ構築
        ...
    validations:
      required: true
  - type: input
    id: related-issue
    attributes:
      label: 関連issue
      description: このPRに関連するissueがある場合は、そのリンクや番号を記載してください。
      placeholder: |
        #123
        マージ時にissueを閉じる場合は、プッシュ時のコミットメッセージの接頭に 'Closes #{issue No.}' を記載してください。
- type: checkboxes
    id: checks
    attributes:
      label: チェックリスト
      description: PR作成者は、以下の項目を確認してください。
      options:
        - label: コードのスタイルガイドラインに従っています。
        - label: コメントを追加・更新し、コードの変更や動作を説明しています。
        - label: ドキュメントを更新しました（必要な場合）。
        - label: 単体テストを追加または更新しました。
  - type: textarea
    id: screenshots
    attributes:
      label: スクリーンショット
      description: 追加機能やバグ解消後の画面のスクリーンショットを追加してください。
  - type: textarea
    id: additional-context
    attributes:
      label: 追加情報
      description: 関連する技術情報、例などがあれば追加してください。