name: docs
description: ドキュメントのみの変更
title: "[docs]: "
labels: ["docs"]
body:
  - type: textarea
    id: description
    attributes:
      label: 改善事項説明
      description: 問題や改善点を記載してください。
      placeholder: Xをすると、Zの代わりにYが発生する。
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: 期待動作
      description: 本来想定していた動作を説明してください。
      placeholder: Xをすると、Aが表示される。
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: 追加情報
      description: 関連する技術情報、例などがあれば追加してください。