name: fix
description: バグ修正
title: "[fix]: "
labels: ["fix"]
body:
  - type: textarea
    id: description
    attributes:
      label: 改善事項説明
      description: 問題や改善点を記載してください。
      placeholder: Xをすると、Zの代わりにYが発生する。
  - type: textarea
    id: reproduction-steps
    attributes:
      label: 再現手順
      description: 不良を再現するための手順を列挙してください。
      placeholder: |
        1. '...'に移動する
        2. '....'をクリックする
        3. '.....'までスクロールする
        4. エラーが表示される
  - type: textarea
    id: expected-behavior
    attributes:
      label: 期待動作
      description: 本来想定していた動作を説明してください。
      placeholder: Xをすると、Aが表示される。
  - type: textarea
    id: screenshots
    attributes:
      label: スクリーンショット
      description: 不良画面のスクリーンショットを追加してください。
  - type: textarea
    id: additional-context
    attributes:
      label: 追加情報
      description: 関連する技術情報、例などがあれば追加してください。